# Generated by Django 2.1.5 on 2019-02-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(unique=True)),
                ('company_name', models.CharField(max_length=250, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('contact_no', models.IntegerField()),
                ('address_line1', models.CharField(max_length=125)),
                ('city', models.CharField(max_length=125)),
                ('state', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deep_diagnose.CompanyDetail')),
            ],
            options={
                'verbose_name_plural': 'CompanyTests',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=125)),
                ('test_details', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Tests',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.AddField(
            model_name='companytests',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deep_diagnose.Tests'),
        ),
    ]
