# Generated by Django 2.1.5 on 2019-02-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_diagnose', '0002_companydetail_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo'),
        ),
    ]
