# Generated by Django 2.1.3 on 2019-02-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deep_diagnose', '0003_auto_20190202_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companytests',
            old_name='test',
            new_name='tests',
        ),
    ]
