# Generated by Django 2.1.5 on 2019-02-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_diagnose', '0004_auto_20190204_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=125)),
                ('email_id', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('address_line_1', models.CharField(max_length=125)),
                ('city', models.CharField(max_length=125)),
                ('state', models.CharField(max_length=125)),
                ('zip_code', models.IntegerField()),
                ('phone_no', models.IntegerField()),
                ('suitable_date', models.DateField()),
                ('suitable_time', models.TimeField()),
            ],
        ),
    ]
