# Generated by Django 2.1.5 on 2019-02-06 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deep_diagnose', '0005_orderinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='order_no',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
